import { createStyles } from 'antd-style';

export const usePointCloudStyles = createStyles(({ token }) => ({
  container: {
    height: 'calc(100vh - 140px)',
    minHeight: 600,
    position: 'relative',
    borderRadius: token.borderRadiusLG,
    overflow: 'hidden',
    background: token.colorBgLayout,
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: '100%',
  },
  selectRect: {
    position: 'absolute',
    border: `1px dashed ${token.colorPrimary}`,
    background: `${token.colorPrimary}15`,
    pointerEvents: 'none',
    display: 'none',
    zIndex: 9,
  },
  panel: {
    position: 'absolute',
    top: token.marginLG,
    left: token.marginLG,
    width: 320,
    maxHeight: `calc(100% - ${token.marginLG * 2}px)`,
    overflowY: 'auto',
    background: token.colorBgElevated,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    padding: token.paddingLG,
    boxShadow: token.boxShadowSecondary,
    zIndex: 10,
    backdropFilter: 'blur(8px)',
  },
  panelTitle: {
    fontSize: token.fontSizeLG,
    fontWeight: 600,
    marginBottom: token.marginMD,
    color: token.colorPrimary,
    borderBottom: `1px solid ${token.colorBorder}`,
    paddingBottom: token.paddingSM,
  },
  row: {
    display: 'flex',
    gap: token.marginSM,
    marginBottom: token.marginSM,
    alignItems: 'center',
  },
  btn: {
    flex: 1,
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: token.fontSizeSM,
    transition: 'all 0.15s ease',
    '&:hover': {
      borderColor: token.colorPrimary,
      color: token.colorPrimary,
    },
  },
  btnActive: {
    background: token.colorPrimaryBg,
    borderColor: token.colorPrimary,
    color: token.colorPrimary,
    fontWeight: 500,
  },
  select: {
    flex: 1,
    height: 32,
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: token.fontSizeSM,
    '&:hover': {
      borderColor: token.colorPrimary,
    },
  },
  info: {
    fontSize: token.fontSizeSM,
    color: token.colorTextSecondary,
    lineHeight: 1.8,
    background: token.colorBgLayout,
    padding: token.paddingSM,
    borderRadius: token.borderRadius,
    marginTop: token.marginSM,
  },
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  infoLabel: {
    color: token.colorTextTertiary,
  },
  infoValue: {
    color: token.colorText,
    fontFamily: 'monospace',
  },
  hint: {
    marginTop: token.marginSM,
    fontSize: token.fontSizeSM,
    color: token.colorTextTertiary,
  },
  footer: {
    position: 'absolute',
    right: token.marginLG,
    bottom: token.marginLG,
    padding: `${token.paddingSM}px ${token.paddingMD}px`,
    fontSize: token.fontSizeSM,
    color: token.colorTextSecondary,
    background: token.colorBgElevated,
    borderRadius: token.borderRadius,
    border: `1px solid ${token.colorBorder}`,
    boxShadow: token.boxShadowTertiary,
  },
}));
