import { createStyles } from 'antd-style';

export const useRobotViewerStyles = createStyles(({ token }) => ({
  container: {
    height: 'calc(100vh - 140px)',
    minHeight: 600,
    position: 'relative',
    borderRadius: token.borderRadiusLG,
    overflow: 'hidden',
    background: token.colorBgLayout,
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: '100%',
  },
  panel: {
    position: 'absolute',
    top: token.marginLG,
    left: token.marginLG,
    width: 360,
    maxHeight: `calc(100% - ${token.marginLG * 2}px)`,
    overflowY: 'auto',
    background: token.colorBgElevated,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    padding: token.paddingLG,
    boxShadow: token.boxShadowSecondary,
    zIndex: 10,
    backdropFilter: 'blur(8px)',
    color: token.colorText,
  },
  panelTitle: {
    fontSize: token.fontSizeLG,
    fontWeight: 600,
    marginBottom: token.marginMD,
    color: token.colorPrimary,
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: token.marginXS,
    marginBottom: token.marginSM,
    flexWrap: 'wrap',
  },
  rowLabel: {
    fontSize: token.fontSize,
    color: token.colorTextSecondary,
    minWidth: 64,
    fontWeight: 500,
  },
  btn: {
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: token.fontSize,
    transition: 'all 0.2s ease',
    '&:hover': {
      borderColor: token.colorPrimary,
      color: token.colorPrimary,
    },
  },
  btnActive: {
    background: token.colorPrimary,
    borderColor: token.colorPrimary,
    color: '#fff',
    '&:hover': {
      background: token.colorPrimaryHover,
      borderColor: token.colorPrimaryHover,
      color: '#fff',
    },
  },
  status: {
    marginTop: token.marginXS,
    fontSize: token.fontSizeSM,
    color: token.colorTextSecondary,
    lineHeight: 1.8,
    background: token.colorBgTextHover,
    padding: token.paddingSM,
    borderRadius: token.borderRadius,
    border: `1px solid ${token.colorBorderSecondary}`,
  },
  transformPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginSM,
    marginTop: token.marginXS,
  },
  transformRow: {
    display: 'grid',
    gridTemplateColumns: '50px 20px 1fr 1fr',
    gap: token.marginXS,
    alignItems: 'center',
  },
  transformAxis: {
    fontSize: token.fontSizeSM,
    color: token.colorTextTertiary,
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  transformInput: {
    width: '100%',
    padding: `${token.paddingXXS}px ${token.paddingXS}px`,
    borderRadius: token.borderRadius,
    border: `1px solid ${token.colorBorder}`,
    background: token.colorBgContainer,
    color: token.colorText,
    fontSize: token.fontSizeSM,
    '&:focus': {
      borderColor: token.colorPrimary,
      outline: 'none',
    },
  },
  transformRange: {
    width: '100%',
    padding: 0,
    height: 20,
  },
  nodeList: {
    maxHeight: 240,
    overflow: 'auto',
    marginTop: token.marginSM,
    padding: token.paddingXS,
    background: token.colorBgTextHover,
    borderRadius: token.borderRadius,
    border: `1px solid ${token.colorBorderSecondary}`,
  },
  nodeItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${token.paddingXXS}px ${token.paddingXS}px`,
    marginBottom: token.marginXXS,
    borderRadius: token.borderRadiusSM,
    fontSize: token.fontSizeSM,
    cursor: 'pointer',
    color: token.colorText,
    background: token.colorBgContainer,
    border: `1px solid transparent`,
    transition: 'all 0.2s ease',
    '&:hover': {
      background: token.colorBgTextHover,
      borderColor: token.colorBorder,
    },
  },
  nodeItemActive: {
    borderColor: token.colorPrimary,
    background: token.colorPrimaryBg,
    color: token.colorPrimary,
    fontWeight: 500,
  },
  nodeLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: token.marginXS,
    minWidth: 0,
    flex: 1,
  },
  nodeLabelText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  footer: {
    position: 'absolute',
    right: token.marginLG,
    bottom: token.marginLG,
    padding: `${token.paddingSM}px ${token.paddingMD}px`,
    fontSize: token.fontSizeSM,
    color: token.colorTextSecondary,
    background: token.colorBgElevated,
    borderRadius: token.borderRadius,
    border: `1px solid ${token.colorBorder}`,
    boxShadow: token.boxShadowTertiary,
  },
  select: {
    flex: 1,
    height: 28,
    padding: 0,
    // margin: 10,
  },
  colorInput: {
    flex: 1,
    height: 28,
    border: 'none',
    background: 'transparent',
    padding: 0,
  },
  section: {
    marginBottom: token.marginMD,
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: `${token.paddingSM}px ${token.paddingMD}px`,
    background: token.colorBgTextHover,
    borderRadius: token.borderRadius,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: token.fontSize,
    color: token.colorText,
    border: `1px solid ${token.colorBorderSecondary}`,
    transition: 'all 0.2s ease',
    '&:hover': {
      background: token.colorBgTextActive,
      borderColor: token.colorBorder,
    },
  },
  sectionContent: {
    padding: `${token.paddingMD}px 0`,
  },
  modeButtonGroup: {
    display: 'flex',
    gap: token.marginXS,
    flex: 1,
  },
  modeButton: {
    flex: 1,
    padding: `${token.paddingXS}px ${token.paddingXS}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: token.fontSizeSM,
    transition: 'all 0.2s ease',
    textAlign: 'center',
    '&:hover': {
      borderColor: token.colorPrimary,
      color: token.colorPrimary,
    },
  },
}));
