import { ContactShadows, Environment, Html, OrbitControls, useGLTF } from '@react-three/drei';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import React, { memo, Suspense, useEffect, useRef, useState } from 'react';
import * as THREE from 'three';

import HeroPage from './HeroPage';

function Model(props) {
  const group = useRef<any>();
  const [dimensions, setDimensions] = useState({ width: 334, height: 216 });
  const { size } = useThree();

  // Load model
  const { nodes, materials } = useGLTF(
    'https://raw.githubusercontent.com/anyone-yuren/multiway/master/mac-draco.glb',
  ) as {
    nodes: any;
    materials: any;
  };

  // 监听窗口大小变化，动态调整Html组件尺寸
  useEffect(() => {
    const updateDimensions = () => {
      const scale = Math.min(size.width / 1200, 1); // 基于容器宽度计算缩放比例
      setDimensions({
        width: Math.max(280, 334 * scale),
        height: Math.max(180, 216 * scale),
      });
    };

    updateDimensions();
    window.addEventListener('resize', updateDimensions);
    return () => window.removeEventListener('resize', updateDimensions);
  }, [size.width]);

  // Make it float
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    if (group.current) {
      group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 2) / 20 + 0.25, 0.1);
      group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 4) / 20, 0.1);
      group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 20, 0.1);
      group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t / 2)) / 2, 0.1);
    }
  });

  // The jsx graph was auto-generated by: https://github.com/pmndrs/gltfjsx
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation-x={-0.425} position={[0, -0.04, 0.41]}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.aluminium} geometry={nodes.Cube008.geometry} />
          <mesh material={materials['matte.001']} geometry={nodes.Cube008_1.geometry} />
          <mesh geometry={nodes.Cube008_2.geometry}>
            {/* Drei's HTML component can "hide behind" canvas geometry */}
            <Html
              className='content'
              style={{
                width: `${dimensions.width}px`,
                height: `${dimensions.height}px`,
                backgroundColor: '#f0f0f0',
                overflowY: 'auto',
                overflowX: 'hidden',
                padding: 0,
                transform: 'translateZ(0)', // 启用硬件加速
                willChange: 'transform', // 优化动画性能
              }}
              rotation-x={-Math.PI / 2}
              position={[0, 0.05, -0.09]}
              transform
              occlude
              // 添加以下属性来优化响应式行为
              center={false} // 禁用自动居中
              distanceFactor={10} // 控制距离因子
              zIndexRange={[100, 0]} // 设置z-index范围
            >
              <div
                className='wrapper'
                style={{
                  padding: '10px',
                  width: `${dimensions.width * 2}px`,
                  height: `${dimensions.height * 2}px`,
                  transform: `scale(${dimensions.width / 668})`,
                  transformOrigin: 'top left',
                  overflow: 'hidden',
                }}
                onPointerDown={(e) => e.stopPropagation()}
              >
                <HeroPage />
              </div>
            </Html>
          </mesh>
        </group>
      </group>
      <mesh material={materials.keys} geometry={nodes.keyboard.geometry} position={[1.79, 0, 3.45]} />
      <group position={[0, -0.1, 3.39]}>
        <mesh material={materials.aluminium} geometry={nodes.Cube002.geometry} />
        <mesh material={materials.trackpad} geometry={nodes.Cube002_1.geometry} />
      </group>
      <mesh material={materials.touchbar} geometry={nodes.touchbar.geometry} position={[0, -0.03, 1.2]} />
    </group>
  );
}

const App = () => {
  return (
    <Canvas
      camera={{ position: [-5, 0, -15], fov: 45 }}
      style={{ width: '100%', height: '450px' }} // 明确设置Canvas尺寸
      resize={{ scroll: true, debounce: { scroll: 50, resize: 50 } }} // 优化resize行为
    >
      <pointLight position={[10, 10, 10]} intensity={1.5} />
      <Suspense fallback={null}>
        <group rotation={[0, Math.PI, 0]} position={[0, 1, 0]}>
          <Model />
        </group>
        <Environment preset='city' />
      </Suspense>
      <ContactShadows position={[0, -4.5, 0]} scale={20} blur={2} far={4.5} />
      <OrbitControls
        enablePan={false}
        enableZoom={false}
        minPolarAngle={Math.PI / 2.2}
        maxPolarAngle={Math.PI / 2.2}
        // 添加以下属性优化控制器
        enableDamping={true}
        dampingFactor={0.05}
      />
    </Canvas>
  );
};

export default memo(App);
