import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    background: token.colorBgLayout,
  },
  canvas: {
    width: '100%',
    height: '100%',
    display: 'block',
  },
  selectRect: {
    position: 'absolute',
    border: '1px dashed',
    borderColor: token.colorPrimary,
    background: `${token.colorPrimary}1a`,
    pointerEvents: 'none',
    display: 'none',
    zIndex: 9,
  },
  panel: {
    position: 'absolute',
    left: 12,
    top: 12,
    zIndex: 10,
    background: `${token.colorBgElevated}f0`,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    padding: '12px 14px',
    minWidth: 280,
    boxShadow: token.boxShadowSecondary,
    backdropFilter: 'blur(8px)',
  },
  panelTitle: {
    fontSize: 15,
    fontWeight: 600,
    marginBottom: 10,
    color: token.colorPrimary,
  },
  row: {
    display: 'flex',
    gap: 8,
    marginBottom: 8,
    alignItems: 'center',
  },
  label: {
    fontSize: 11,
    color: token.colorTextSecondary,
    minWidth: 70,
  },
  btn: {
    flex: 1,
    padding: '6px 10px',
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: 12,
    transition: 'all 0.15s ease',
    '&:hover': {
      borderColor: token.colorPrimary,
    },
  },
  btnActive: {
    background: token.colorPrimaryBg,
    borderColor: token.colorPrimary,
    color: token.colorPrimary,
  },
  select: {
    flex: 1,
    padding: '6px 10px',
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
    color: token.colorText,
    cursor: 'pointer',
    fontSize: 12,
    '&:hover': {
      borderColor: token.colorPrimary,
    },
  },
  range: {
    flex: 1,
    cursor: 'ew-resize',
  },
  rangeValue: {
    minWidth: 50,
    textAlign: 'right' as const,
    fontSize: 12,
    color: token.colorText,
  },
  info: {
    fontSize: 11,
    color: token.colorTextSecondary,
    lineHeight: 1.7,
    background: `${token.colorBgLayout}80`,
    padding: 8,
    borderRadius: token.borderRadius,
    width: 256,
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  infoValue: {
    textAlign: 'right' as const,
    minWidth: 120,
    fontVariantNumeric: 'tabular-nums',
  },
  infoHighlight: {
    color: token.colorWarning,
    fontWeight: 500,
  },
  hint: {
    marginTop: 8,
    fontSize: 11,
    color: token.colorTextTertiary,
  },
}));
